# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edaa0b6a5b703bb33a538b6e4946882dfa5d045d28274dd5459ae62c8623bd2fac93005dbdd4404efda4faf13b7af8fa891ab3c2ad8168ca3112e448dc1b5f09

test:
  secret_key_base: 8acd4b3fe47d30b010051e35bd817c8c2b6cdd11a32c9dc3fafe8a7c77ff980ba9b0790d5d44bd57e0cc2b7e24d4884efe5f6acc3568501871f024e9d5b8b85b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
